/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "ERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC20__factory>;
    getContractFactory(
      name: "IERC20Metadata",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Metadata__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "ITimeswapBorrowCallback",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ITimeswapBorrowCallback__factory>;
    getContractFactory(
      name: "ITimeswapLendCallback",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ITimeswapLendCallback__factory>;
    getContractFactory(
      name: "ITimeswapMintCallback",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ITimeswapMintCallback__factory>;
    getContractFactory(
      name: "ITimeswapPayCallback",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ITimeswapPayCallback__factory>;
    getContractFactory(
      name: "IFactory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IFactory__factory>;
    getContractFactory(
      name: "IPair",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IPair__factory>;
    getContractFactory(
      name: "ArrayTest",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ArrayTest__factory>;
    getContractFactory(
      name: "BlockNumberTest",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.BlockNumberTest__factory>;
    getContractFactory(
      name: "BorrowMathTest",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.BorrowMathTest__factory>;
    getContractFactory(
      name: "BurnMathTest",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.BurnMathTest__factory>;
    getContractFactory(
      name: "CallbackTest",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CallbackTest__factory>;
    getContractFactory(
      name: "CallbackTestCallee",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CallbackTestCallee__factory>;
    getContractFactory(
      name: "ConstantProductTest",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ConstantProductTest__factory>;
    getContractFactory(
      name: "FullMathTest",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.FullMathTest__factory>;
    getContractFactory(
      name: "LendMathTest",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.LendMathTest__factory>;
    getContractFactory(
      name: "MathTest",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MathTest__factory>;
    getContractFactory(
      name: "MintMathTest",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MintMathTest__factory>;
    getContractFactory(
      name: "PayMathTest",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PayMathTest__factory>;
    getContractFactory(
      name: "SafeBalanceTest",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SafeBalanceTest__factory>;
    getContractFactory(
      name: "SafeCastTest",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SafeCastTest__factory>;
    getContractFactory(
      name: "SafeTransferTest",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SafeTransferTest__factory>;
    getContractFactory(
      name: "WithdrawMathTest",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.WithdrawMathTest__factory>;
    getContractFactory(
      name: "TestToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TestToken__factory>;
    getContractFactory(
      name: "TimeswapPairCallee",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TimeswapPairCallee__factory>;
    getContractFactory(
      name: "TimeswapFactory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TimeswapFactory__factory>;
    getContractFactory(
      name: "TimeswapPair",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TimeswapPair__factory>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
  }
}
