/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface WithdrawMathTestInterface extends ethers.utils.Interface {
  functions: {
    "getAsset(tuple,uint128)": FunctionFragment;
    "getCollateral(tuple,uint128)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getAsset",
    values: [
      {
        reserves: { asset: BigNumberish; collateral: BigNumberish };
        totalLiquidity: BigNumberish;
        totalClaims: { bond: BigNumberish; insurance: BigNumberish };
        totalDebtCreated: BigNumberish;
        x: BigNumberish;
        y: BigNumberish;
        z: BigNumberish;
      },
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getCollateral",
    values: [
      {
        reserves: { asset: BigNumberish; collateral: BigNumberish };
        totalLiquidity: BigNumberish;
        totalClaims: { bond: BigNumberish; insurance: BigNumberish };
        totalDebtCreated: BigNumberish;
        x: BigNumberish;
        y: BigNumberish;
        z: BigNumberish;
      },
      BigNumberish
    ]
  ): string;

  decodeFunctionResult(functionFragment: "getAsset", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getCollateral",
    data: BytesLike
  ): Result;

  events: {};
}

export class WithdrawMathTest extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: WithdrawMathTestInterface;

  functions: {
    getAsset(
      state: {
        reserves: { asset: BigNumberish; collateral: BigNumberish };
        totalLiquidity: BigNumberish;
        totalClaims: { bond: BigNumberish; insurance: BigNumberish };
        totalDebtCreated: BigNumberish;
        x: BigNumberish;
        y: BigNumberish;
        z: BigNumberish;
      },
      bondIn: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { assetOut: BigNumber }>;

    "getAsset(((uint128,uint128),uint256,(uint128,uint128),uint120,uint112,uint112,uint112),uint128)"(
      state: {
        reserves: { asset: BigNumberish; collateral: BigNumberish };
        totalLiquidity: BigNumberish;
        totalClaims: { bond: BigNumberish; insurance: BigNumberish };
        totalDebtCreated: BigNumberish;
        x: BigNumberish;
        y: BigNumberish;
        z: BigNumberish;
      },
      bondIn: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { assetOut: BigNumber }>;

    getCollateral(
      state: {
        reserves: { asset: BigNumberish; collateral: BigNumberish };
        totalLiquidity: BigNumberish;
        totalClaims: { bond: BigNumberish; insurance: BigNumberish };
        totalDebtCreated: BigNumberish;
        x: BigNumberish;
        y: BigNumberish;
        z: BigNumberish;
      },
      insuranceIn: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { collateralOut: BigNumber }>;

    "getCollateral(((uint128,uint128),uint256,(uint128,uint128),uint120,uint112,uint112,uint112),uint128)"(
      state: {
        reserves: { asset: BigNumberish; collateral: BigNumberish };
        totalLiquidity: BigNumberish;
        totalClaims: { bond: BigNumberish; insurance: BigNumberish };
        totalDebtCreated: BigNumberish;
        x: BigNumberish;
        y: BigNumberish;
        z: BigNumberish;
      },
      insuranceIn: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { collateralOut: BigNumber }>;
  };

  getAsset(
    state: {
      reserves: { asset: BigNumberish; collateral: BigNumberish };
      totalLiquidity: BigNumberish;
      totalClaims: { bond: BigNumberish; insurance: BigNumberish };
      totalDebtCreated: BigNumberish;
      x: BigNumberish;
      y: BigNumberish;
      z: BigNumberish;
    },
    bondIn: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "getAsset(((uint128,uint128),uint256,(uint128,uint128),uint120,uint112,uint112,uint112),uint128)"(
    state: {
      reserves: { asset: BigNumberish; collateral: BigNumberish };
      totalLiquidity: BigNumberish;
      totalClaims: { bond: BigNumberish; insurance: BigNumberish };
      totalDebtCreated: BigNumberish;
      x: BigNumberish;
      y: BigNumberish;
      z: BigNumberish;
    },
    bondIn: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getCollateral(
    state: {
      reserves: { asset: BigNumberish; collateral: BigNumberish };
      totalLiquidity: BigNumberish;
      totalClaims: { bond: BigNumberish; insurance: BigNumberish };
      totalDebtCreated: BigNumberish;
      x: BigNumberish;
      y: BigNumberish;
      z: BigNumberish;
    },
    insuranceIn: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "getCollateral(((uint128,uint128),uint256,(uint128,uint128),uint120,uint112,uint112,uint112),uint128)"(
    state: {
      reserves: { asset: BigNumberish; collateral: BigNumberish };
      totalLiquidity: BigNumberish;
      totalClaims: { bond: BigNumberish; insurance: BigNumberish };
      totalDebtCreated: BigNumberish;
      x: BigNumberish;
      y: BigNumberish;
      z: BigNumberish;
    },
    insuranceIn: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    getAsset(
      state: {
        reserves: { asset: BigNumberish; collateral: BigNumberish };
        totalLiquidity: BigNumberish;
        totalClaims: { bond: BigNumberish; insurance: BigNumberish };
        totalDebtCreated: BigNumberish;
        x: BigNumberish;
        y: BigNumberish;
        z: BigNumberish;
      },
      bondIn: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getAsset(((uint128,uint128),uint256,(uint128,uint128),uint120,uint112,uint112,uint112),uint128)"(
      state: {
        reserves: { asset: BigNumberish; collateral: BigNumberish };
        totalLiquidity: BigNumberish;
        totalClaims: { bond: BigNumberish; insurance: BigNumberish };
        totalDebtCreated: BigNumberish;
        x: BigNumberish;
        y: BigNumberish;
        z: BigNumberish;
      },
      bondIn: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getCollateral(
      state: {
        reserves: { asset: BigNumberish; collateral: BigNumberish };
        totalLiquidity: BigNumberish;
        totalClaims: { bond: BigNumberish; insurance: BigNumberish };
        totalDebtCreated: BigNumberish;
        x: BigNumberish;
        y: BigNumberish;
        z: BigNumberish;
      },
      insuranceIn: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getCollateral(((uint128,uint128),uint256,(uint128,uint128),uint120,uint112,uint112,uint112),uint128)"(
      state: {
        reserves: { asset: BigNumberish; collateral: BigNumberish };
        totalLiquidity: BigNumberish;
        totalClaims: { bond: BigNumberish; insurance: BigNumberish };
        totalDebtCreated: BigNumberish;
        x: BigNumberish;
        y: BigNumberish;
        z: BigNumberish;
      },
      insuranceIn: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    getAsset(
      state: {
        reserves: { asset: BigNumberish; collateral: BigNumberish };
        totalLiquidity: BigNumberish;
        totalClaims: { bond: BigNumberish; insurance: BigNumberish };
        totalDebtCreated: BigNumberish;
        x: BigNumberish;
        y: BigNumberish;
        z: BigNumberish;
      },
      bondIn: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getAsset(((uint128,uint128),uint256,(uint128,uint128),uint120,uint112,uint112,uint112),uint128)"(
      state: {
        reserves: { asset: BigNumberish; collateral: BigNumberish };
        totalLiquidity: BigNumberish;
        totalClaims: { bond: BigNumberish; insurance: BigNumberish };
        totalDebtCreated: BigNumberish;
        x: BigNumberish;
        y: BigNumberish;
        z: BigNumberish;
      },
      bondIn: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getCollateral(
      state: {
        reserves: { asset: BigNumberish; collateral: BigNumberish };
        totalLiquidity: BigNumberish;
        totalClaims: { bond: BigNumberish; insurance: BigNumberish };
        totalDebtCreated: BigNumberish;
        x: BigNumberish;
        y: BigNumberish;
        z: BigNumberish;
      },
      insuranceIn: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getCollateral(((uint128,uint128),uint256,(uint128,uint128),uint120,uint112,uint112,uint112),uint128)"(
      state: {
        reserves: { asset: BigNumberish; collateral: BigNumberish };
        totalLiquidity: BigNumberish;
        totalClaims: { bond: BigNumberish; insurance: BigNumberish };
        totalDebtCreated: BigNumberish;
        x: BigNumberish;
        y: BigNumberish;
        z: BigNumberish;
      },
      insuranceIn: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getAsset(
      state: {
        reserves: { asset: BigNumberish; collateral: BigNumberish };
        totalLiquidity: BigNumberish;
        totalClaims: { bond: BigNumberish; insurance: BigNumberish };
        totalDebtCreated: BigNumberish;
        x: BigNumberish;
        y: BigNumberish;
        z: BigNumberish;
      },
      bondIn: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getAsset(((uint128,uint128),uint256,(uint128,uint128),uint120,uint112,uint112,uint112),uint128)"(
      state: {
        reserves: { asset: BigNumberish; collateral: BigNumberish };
        totalLiquidity: BigNumberish;
        totalClaims: { bond: BigNumberish; insurance: BigNumberish };
        totalDebtCreated: BigNumberish;
        x: BigNumberish;
        y: BigNumberish;
        z: BigNumberish;
      },
      bondIn: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getCollateral(
      state: {
        reserves: { asset: BigNumberish; collateral: BigNumberish };
        totalLiquidity: BigNumberish;
        totalClaims: { bond: BigNumberish; insurance: BigNumberish };
        totalDebtCreated: BigNumberish;
        x: BigNumberish;
        y: BigNumberish;
        z: BigNumberish;
      },
      insuranceIn: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getCollateral(((uint128,uint128),uint256,(uint128,uint128),uint120,uint112,uint112,uint112),uint128)"(
      state: {
        reserves: { asset: BigNumberish; collateral: BigNumberish };
        totalLiquidity: BigNumberish;
        totalClaims: { bond: BigNumberish; insurance: BigNumberish };
        totalDebtCreated: BigNumberish;
        x: BigNumberish;
        y: BigNumberish;
        z: BigNumberish;
      },
      insuranceIn: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
