/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { FullMathTest, FullMathTestInterface } from "../FullMathTest";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "a",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "b",
        type: "uint256",
      },
    ],
    name: "mul512",
    outputs: [
      {
        internalType: "uint256",
        name: "prod0",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "prod1",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "a",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "b",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "denominator",
        type: "uint256",
      },
    ],
    name: "mulDiv",
    outputs: [
      {
        internalType: "uint256",
        name: "result",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "a",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "b",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "denominator",
        type: "uint256",
      },
    ],
    name: "mulDivUp",
    outputs: [
      {
        internalType: "uint256",
        name: "result",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b506102a1806100206000396000f3fe608060405234801561001057600080fd5b50600436106100415760003560e01c806312bd6ac01461004657806373d0b5121461006c578063aa9a091214610094575b600080fd5b610059610054366004610219565b6100a7565b6040519081526020015b60405180910390f35b61007f61007a3660046101f8565b6100be565b60408051928352602083019190915201610063565b6100596100a2366004610219565b6100d6565b60006100b48484846100e3565b90505b9392505050565b6000806100cb848461012c565b915091509250929050565b60006100b484848461014b565b60006100f084848461014b565b90506000828061011057634e487b7160e01b600052601260045260246000fd5b84860911156100b7578061012381610244565b95945050505050565b6000806000198385098385029250828110838203039150509250929050565b600080600061015a868661012c565b91509150806000141561017f576000841161017457600080fd5b5082900490506100b7565b80841161018b57600080fd5b6000848688096000868103871696879004966002600389028118808a02820302808a02820302808a02820302808a02820302808a02820302808a02909103029181900381900460010186841190950394909402919094039290920491909117919091029150509392505050565b6000806040838503121561020a578182fd5b50508035926020909101359150565b60008060006060848603121561022d578081fd5b505081359360208301359350604090920135919050565b600060001982141561026457634e487b7160e01b81526011600452602481fd5b506001019056fea26469706673582212207c717ee1ac49344fe65126709e635b01a1619abf670385eb57b15974dfc1293e64736f6c63430008040033";

export class FullMathTest__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<FullMathTest> {
    return super.deploy(overrides || {}) as Promise<FullMathTest>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): FullMathTest {
    return super.attach(address) as FullMathTest;
  }
  connect(signer: Signer): FullMathTest__factory {
    return super.connect(signer) as FullMathTest__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): FullMathTestInterface {
    return new utils.Interface(_abi) as FullMathTestInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): FullMathTest {
    return new Contract(address, _abi, signerOrProvider) as FullMathTest;
  }
}
