/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  ITimeswapMintCallback,
  ITimeswapMintCallbackInterface,
} from "../ITimeswapMintCallback";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint112",
        name: "assetIn",
        type: "uint112",
      },
      {
        internalType: "uint112",
        name: "collateralIn",
        type: "uint112",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "timeswapMintCallback",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ITimeswapMintCallback__factory {
  static readonly abi = _abi;
  static createInterface(): ITimeswapMintCallbackInterface {
    return new utils.Interface(_abi) as ITimeswapMintCallbackInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ITimeswapMintCallback {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ITimeswapMintCallback;
  }
}
