/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  ITimeswapBorrowCallback,
  ITimeswapBorrowCallbackInterface,
} from "../ITimeswapBorrowCallback";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint112",
        name: "collateralIn",
        type: "uint112",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "timeswapBorrowCallback",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ITimeswapBorrowCallback__factory {
  static readonly abi = _abi;
  static createInterface(): ITimeswapBorrowCallbackInterface {
    return new utils.Interface(_abi) as ITimeswapBorrowCallbackInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ITimeswapBorrowCallback {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ITimeswapBorrowCallback;
  }
}
