/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  ITimeswapLendCallback,
  ITimeswapLendCallbackInterface,
} from "../ITimeswapLendCallback";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint112",
        name: "assetIn",
        type: "uint112",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "timeswapLendCallback",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ITimeswapLendCallback__factory {
  static readonly abi = _abi;
  static createInterface(): ITimeswapLendCallbackInterface {
    return new utils.Interface(_abi) as ITimeswapLendCallbackInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ITimeswapLendCallback {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ITimeswapLendCallback;
  }
}
