/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { SafeCastTest, SafeCastTestInterface } from "../SafeCastTest";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "x",
        type: "uint256",
      },
    ],
    name: "modUint32",
    outputs: [
      {
        internalType: "uint32",
        name: "y",
        type: "uint32",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "x",
        type: "uint256",
      },
    ],
    name: "toUint112",
    outputs: [
      {
        internalType: "uint112",
        name: "y",
        type: "uint112",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "x",
        type: "uint256",
      },
    ],
    name: "toUint128",
    outputs: [
      {
        internalType: "uint128",
        name: "y",
        type: "uint128",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "x",
        type: "uint256",
      },
    ],
    name: "truncateUint112",
    outputs: [
      {
        internalType: "uint112",
        name: "y",
        type: "uint112",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b506101ec806100206000396000f3fe608060405234801561001057600080fd5b506004361061004c5760003560e01c80633a06080e1461005157806341d2aa6414610081578063809fdd3314610094578063b5514309146100bf575b600080fd5b61006461005f36600461017e565b6100e7565b6040516001600160701b0390911681526020015b60405180910390f35b61006461008f36600461017e565b6100f8565b6100a76100a236600461017e565b610103565b6040516001600160801b039091168152602001610078565b6100d26100cd36600461017e565b61010e565b60405163ffffffff9091168152602001610078565b60006100f282610119565b92915050565b60006100f28261013c565b60006100f282610157565b60006100f28261016d565b60006001600160701b0382111561013857506001600160701b03919050565b5090565b806001600160701b038116811461015257600080fd5b919050565b806001600160801b038116811461015257600080fd5b60006100f264010000000083610196565b60006020828403121561018f578081fd5b5035919050565b6000826101b157634e487b7160e01b81526012600452602481fd5b50069056fea264697066735822122010fe1fc691ce50a73013382c138dea70c200bea133c6ff3d43ebb17484b606ca64736f6c63430008040033";

export class SafeCastTest__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<SafeCastTest> {
    return super.deploy(overrides || {}) as Promise<SafeCastTest>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): SafeCastTest {
    return super.attach(address) as SafeCastTest;
  }
  connect(signer: Signer): SafeCastTest__factory {
    return super.connect(signer) as SafeCastTest__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): SafeCastTestInterface {
    return new utils.Interface(_abi) as SafeCastTestInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): SafeCastTest {
    return new Contract(address, _abi, signerOrProvider) as SafeCastTest;
  }
}
